cadenacacao/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from directorio.views import *
from context import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
#from mensajes.views import enviar_correo


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^enviar/', include('mensajes.urls', namespace="mensajes", app_name="mensajes")),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^actores/busqueda/', include('haystack.urls')),
    #url(r'^correo/permiso-org/', enviar_correo_pedir_permiso, name="permiso-admin"),
    url(r'^correo/admin/', enviar_correo_administradores, name="soporte-admin"),
    #url(r'^enviar/correo/', enviar_correo, name="envio-correo"),
    # url(r'^accounts/register/$',MyRegistrationView.as_view(),name='registration_register'),

    # url(r'^accounts/logout/$', auth_views.logout,{'next_page': '/'}),
    url(r'^accounts/profile/$',user_profile,name='profile'),
    url(r'^accounts/profile/crear/$',crear_org,name='crear-org'),
    url(r'^accounts/profile/editar/(?P<slug>[\w-]+)/$',editar_org,name='editar-org'),
    url(r'^accounts/profile/user/editar/$',editar_user,name='editar-user'),
    url(r'^permisos/editar/(?P<user_id>[0-9]+)/(?P<org_id>[0-9]+)/$',permisos_organizacion,name='editar-permisos-user'),

    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    #url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^buscador/$', buscador, name='search'),
    url(r'^actores/$', consulta, name='consulta'),
    url(r'^actores/perfil/(?P<slug>[\w-]+)/$', detail_org, name='detail-org'),
    url(r'^mapa/$', obtener_lista, name='obtener-lista'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^politica-condiciones/$', TemplateView.as_view(template_name="policy-service.html")),
    url(r'^servicios/$', Servicios.as_view()),

    #template correo
    #url(r'^correo/$', TemplateView.as_view(template_name="correo.html")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

mensajes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^correo/', views.enviar_correo, name="enviar_correo"),
]

directorio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from location_field.models.plain import PlainLocationField
from sorl.thumbnail import ImageField
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from django.utils.encoding import python_2_unicode_compatible
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
@python_2_unicode_compatible
class Pais(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = 'País'
		verbose_name_plural = 'Paises'
		ordering = ('nombre',)

@python_2_unicode_compatible
class TipoActividad(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = 'Tipo de actividad'
		verbose_name_plural = 'Tipos de actividades'

@python_2_unicode_compatible
class Participacion(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = 'Participación en la cadena de valor'

@python_2_unicode_compatible
class ServiciosCadena(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = 'Servicios en la Cadena de Valor'

@python_2_unicode_compatible
class IntercambioTecnologia(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = 'Intercambio de Tecnología'

TIPO_CHOICES = (
		('Sector publico','Gobierno'),('Sector privado','Empresa'),('Academia','Academia'),
		('Asociacion','Asociación'),('Cooperativa','Cooperativa'),('Fundacion','Fundación'),
		('ONG','ONG'),('ONGI','ONGI'),('Plataforma','Plataforma'),('Consultor','Consultor'),
		('Financiera', 'Financiera'),('Banco', 'Banco'),
		('Centro Investigacion', 'Centro de investigación')
	)

AMBITO_CHOICES = (
		('Internacional','Internacional'),('Regional','Regional'),
		('Nacional','Nacional'),('Local','Local')
	)

PERIODO_CHOICES = (
		('2 años','2 años'),('3 años','3 años'),
		('4 años','4 años'),('5 años','5 años'),
		('Mas de 5 años','Más de 5 años')
	)

# ESP_ORG_CHOICES = (
# 	('Organizacion','Organización'),('Especialista','Especialista'))

@python_2_unicode_compatible
class Organizacion(models.Model):
	# tipo = models.CharField(max_length=20,choices=ESP_ORG_CHOICES)
	nombre = models.CharField(max_length=255)
	logo = ImageField(upload_to='logos/',blank=True,null=True,help_text='Las dimenciones de la imagen son 200x200')
	objetivo = RichTextUploadingField(verbose_name='Descripción de la Organización')
	contacto_1 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Persona de Contacto 1')
	correo_1 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Correo 1')
	telefono_1 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Teléfono 1')
	contacto_2 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Persona de Contacto 2')
	correo_2 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Correo 2')
	telefono_2 = models.CharField(max_length=255,blank=True,null=True,verbose_name='Teléfono 2')
	pais_sede = models.ForeignKey(Pais,verbose_name='País Sede')
	ciudad = models.CharField(max_length=255,blank=True,null=True,help_text='Cuidad donde esta ubicada o dirección',verbose_name='Ciudad/Dirección')
	location = PlainLocationField(based_fields=['ciudad'], zoom=5,blank=True,null=True,verbose_name='Ubicación')
	tipo_organizacion = models.CharField(max_length=20,choices=TIPO_CHOICES,verbose_name='Tipo de Organización')
	#tipo_actividad = models.ManyToManyField(TipoActividad,verbose_name='Tipo de Actividad')
	participacion_cadena = models.ManyToManyField(Participacion,verbose_name='Participación en la Cadena de Valor')
	servicios = models.ManyToManyField(ServiciosCadena,verbose_name='Servicios que brinda la Organización')
	ambito_accion = models.CharField(max_length=20,choices=AMBITO_CHOICES,verbose_name='Ámbito de Acción')
	paises_labora = models.ManyToManyField(Pais,related_name='Paises',verbose_name='Países donde Labora')
	#cobertura = models.CharField(max_length=255,verbose_name='Cobertura Geográfica')
	# periodo_permanencia = models.CharField(max_length=20,choices=PERIODO_CHOICES,verbose_name='Período de Permanencia')
	# intercambio = models.ManyToManyField(IntercambioTecnologia,verbose_name='Intercambio de Tecnología')
	sitio_web = models.URLField(blank=True,null=True)
	miembros = models.IntegerField(blank=True,null=True,verbose_name='N° de Miembros/Socio')
	# tamano = models.CharField(max_length=20,blank=True,null=True,verbose_name='Tamaño')
	actualizado = models.DateField(editable=False,auto_now=True)
	slug = models.SlugField(editable=False, max_length=450)
	ratings = GenericRelation(Rating, related_query_name='object_list')
	usuario = models.ManyToManyField(User,blank=True)

	def save(self, *args, **kwargs):
		# if not self.id:
		self.slug = slugify(self.nombre)
		super(Organizacion, self).save(*args, **kwargs)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = 'Organización/Especialista'
		verbose_name_plural = 'Organizaciones/Especialistas'
		ordering = ['-id']

REDES_CHOICES = (('Sitio web','Sitio web'),('Facebook','Facebook'),('Twitter','Twitter'),('Youtube','Youtube'),
					('Google+','Google+'),('Instagram','Instagram'),('Linkedin','Linkedin'),
					('Flickr','Flickr'),('Pinterest','Pinterest'),('Vimeo','Vimeo'),('Otra','Otra'),)

class LinkVideos(models.Model):
	organizacion = models.ForeignKey(Organizacion)
	titulo = models.CharField(max_length=250, null=True)
	url = models.URLField()

	class Meta:
		verbose_name = 'Link de Videos'
		verbose_name_plural = 'Link de Videos'

class Redes(models.Model):
	organizacion = models.ForeignKey(Organizacion)
	opcion = models.CharField(max_length=25,choices=REDES_CHOICES)
	url = models.URLField()

	class Meta:
		verbose_name = 'Red'
		verbose_name_plural = 'Redes'

class ProductosServicios(models.Model):
	organizacion = models.ForeignKey(Organizacion)
	nombre = models.CharField(max_length=255)
	descripcion = models.CharField('Descripción', max_length=200, null=True, blank=True)
	foto = ImageField(upload_to='productos-servicios/')

	class Meta:
		verbose_name = 'Producto/Servicio'
		verbose_name_plural = 'Productos y Servicios'

mensajes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from directorio.models import Pais, TIPO_CHOICES, Participacion, Organizacion
# Create your models here.

class Mensaje(models.Model):
    pais = models.ManyToManyField(Pais, blank=True)
    tipo_organizacion = models.CharField(max_length=20, choices=TIPO_CHOICES, null=True, blank=True)
    participacion_cadena = models.ManyToManyField(Participacion, blank=True)
    destinatario = models.ManyToManyField(Organizacion, blank=True)
    asunto = models.CharField(max_length=300)
    contenido = models.TextField()

    usuario = models.ForeignKey(User)

    class Meta:
        verbose_name = "Mensaje"
        verbose_name_plural = "Mensajes"

    def __str__(self):
        return self.asunto
    

directorio/forms.py
# -*- coding: UTF-8 -*-
from django.db import models
from .models import *
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget

def paises():
	foo = Organizacion.objects.order_by('pais_sede').distinct().values_list('pais_sede__id', flat=True)
	return Pais.objects.filter(id__in=foo)

def paises_labora():
	foo = Organizacion.objects.order_by('paises_labora').distinct().values_list('paises_labora__id', flat=True)
	return Pais.objects.filter(id__in=foo)

AMBITO_CHOICES = (
		('','------'),('Internacional','Internacional'),('Regional','Regional'),
		('Nacional','Nacional'),('Local','Local')
	)

TIPO_CHOICES = (
		('Sector publico','Gobierno'),('Sector privado','Empresa'),('Academia','Academia'),
		('Asociacion','Asociación'),('Cooperativa','Cooperativa'),('Fundacion','Fundación'),
		('ONG','ONG'),('ONGI','ONGI'),('Plataforma','Plataforma'),('Consultor','Consultor'),
		('Financiera', 'Financiera'),('Banco', 'Banco'),
		('Centro Investigacion', 'Centro de investigación')
	)

# ESP_ORG_CHOICES = (('','Seleccione'),
# 	('Organizacion','Organización'),('Especialista','Especialista'))

class OrganizacionForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(OrganizacionForm, self).__init__(*args, **kwargs)
		self.fields['pais_sede'] = forms.ModelChoiceField(queryset=paises(),required=True)
		self.fields['ambito_accion'] = forms.ChoiceField(choices=AMBITO_CHOICES,required=False)
		self.fields['tipo_organizacion'] = forms.MultipleChoiceField(choices=TIPO_CHOICES,required=False)
		self.fields['paises_labora'] = forms.ModelMultipleChoiceField(queryset=paises_labora(),required=False)
		self.fields['participacion_cadena'] = forms.ModelMultipleChoiceField(queryset=Participacion.objects.all(),required=False)
		self.fields['servicios'] = forms.ModelMultipleChoiceField(queryset=ServiciosCadena.objects.all(),required=False)
		# self.fields['intercambio'] = forms.ModelMultipleChoiceField(queryset=IntercambioTecnologia.objects.all(),required=False)
		# self.fields['tipo'] = forms.ChoiceField(choices=ESP_ORG_CHOICES,required=False)
		#self.fields['tipo_actividad'] = forms.ModelMultipleChoiceField(queryset=TipoActividad.objects.all(),required=False)

class BuscadorForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(BuscadorForm, self).__init__(*args, **kwargs)
		self.fields['q'] = forms.CharField()

class OrgForm(forms.ModelForm):
	objetivo = forms.CharField(label='Descripción de la Organización',max_length=3000,widget=CKEditorUploadingWidget)
	class Meta:
		model = Organizacion
		fields = '__all__'
		exclude = ['usuario',]


class ProductosServiciosFrom(forms.ModelForm):
	nombre = models.CharField(max_length=30)
	class Meta:
		model = ProductosServicios
		fields = '__all__'
		exclude = ['organizacion',]

class RedesFrom(forms.ModelForm):
	class Meta:
		model = Redes
		fields = '__all__'
		exclude = ['organizacion',]

class VideosForm(forms.ModelForm):
	class Meta:
		model = LinkVideos
		fields = '__all__'
		exclude = ['organizacion',]

class EmailForm(forms.Form):
	mensaje = forms.CharField(widget=forms.Textarea,label="Descripción breve",max_length=2000)

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username','email','first_name', 'last_name',)

class PermisoFormOrganizacion(forms.ModelForm):
	class Meta:
		model = Organizacion
		fields = ('nombre','usuario',)

class PedirPermisoForm(forms.Form):
	cual_org = forms.ModelChoiceField(queryset=Organizacion.objects.all(),
	                                           required=True,
	                                           label="Organización")
	asunto = forms.CharField( widget=forms.Textarea )

mensajes/forms.py
from django import forms
from directorio.models import Organizacion, Participacion, TIPO_CHOICES, Pais
from .models import *
from ckeditor_uploader.widgets import CKEditorUploadingWidget


def paises():
    foo = Organizacion.objects.order_by('pais_sede').distinct().values_list('pais_sede__id', flat=True)
    return Pais.objects.filter(id__in=foo)

class MensajeForm(forms.ModelForm):
    pais = forms.ModelMultipleChoiceField(queryset=Pais.objects.all(),
            required=False,  widget=forms.SelectMultiple(attrs={"class":"prueba form-control"}))
    tipo_organizacion = forms.ChoiceField(choices=TIPO_CHOICES,
                                        required=False,  widget=forms.Select(attrs={"class":"prueba form-control"}))
    participacion_cadena = forms.ModelMultipleChoiceField(queryset=Participacion.objects.all(),
                                            required=False,  widget=forms.SelectMultiple(attrs={"class":"prueba form-control"}))
    destinatario = forms.ModelMultipleChoiceField(queryset=Organizacion.objects.all(),
                                    required=False, widget=forms.SelectMultiple(attrs={"class":"prueba form-control"}))
    asunto = forms.CharField( widget=forms.TextInput(attrs={"class":"prueba form-control"}))
    contenido = forms.CharField(widget=CKEditorUploadingWidget(attrs={"rows":10, "cols":40,"class":"form-control"}))
    class Meta:
        model=Mensaje
        fields = ('pais', 'tipo_organizacion', 
                  'participacion_cadena', 'destinatario',
                  'asunto', 'contenido')

templates/detalle.html
{% load ratings %}
<html>

<h1>{{object.nombre}}</h1>
{% ratings object %}
</html>

templates/editar_permisos.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
{% endblock extra_css %}

{% block content %}
    <section>
        <ol class="breadcrumb">
            <li><a href="/accounts/profile/">Perfil de usuario</a></li>
            <li class="active">Editar permisos</li>
        </ol>
    </section>
<section class="section-grey small-padding">

        <!--begin container-->
        <div class="container ">

            <div class="row">

                <div class="col-md-offset-2 col-md-8 detalle-user">
                    <h1 class="">Editar permiso </h1>
                    <h5>Le desea otorgar permiso al usuario: <strong>{{usuario}}</strong> sobre el perfil de la Organización <strong>{{organizacion}}</strong>?</h5>
                    {% if alerta %}
                        <p><div class="alert alert-danger" role="alert">
                              {{alerta}}
                            </div></p>
                    {% endif %}


                    <div>
                        <input type="hidden" id="permisito" value="SI">
                        <input onclick="setGetParameter()" type="button" class="btn btn-success" value = "Agregar permiso" {% if alerta %} disabled {% endif %}/>
                        <a href="/accounts/profile" class="btn btn-danger">{% if alerta %} Regresar al perfil {%else%}No {% endif %}</a>
                    </div>


                    <script>

                    function setGetParameter(){
                        var search_word = $("#permisito").val();
                        $.ajax({
                          type: "POST",
                          url: "{% url 'editar-permisos-user' usuario.id organizacion.id %}",
                          data: {
                            'data': search_word,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                            },
                          success: function(result){
                            alert("Permiso Otorgado");
                            window.location = "/accounts/profile";
                          }
                        });
                    }
                    </script>
                </div>
            </div>

        </div>
    </section>


{% endblock content %}

{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<script type="text/javascript">
    $("#id_nombre").prop("readonly", true);
    $('#id_usuario').select2();

</script>
{% endblock extra_js %}

templates/editar_user.html
{% extends "base.html" %}

{% block content %}
	<section>
		<ol class="breadcrumb">
			<li><a href="/accounts/profile/">Perfil de usuario</a></li>
			<li class="active">Editar perfil</li>
		</ol>
	</section>
	<section class="section-grey small-padding">
        
        <!--begin container-->
        <div class="container detalle-user">
        	
        	<div class="row">

        		<div class="col-xs-12 col-md-8 col-md-offset-2">
        			<h1 class="">Editar perfil de usuario</h1>
        			<form method="POST" id="contact-form">{% csrf_token %}
						<div class="row">
							<div class="col-xs-12 col-sm-6">
					            <div class="input-group group-costum-2">
					                <span class="input-group-addon " id="sizing-addon2">Nombre</span>
									{{form.first_name}} 

								</div>
					        </div>
					        <div class="col-xs-12 col-sm-6">
					            <div class="input-group group-costum-2">
					                <span class="input-group-addon " id="sizing-addon2">Apellidos:</span>
									{{form.last_name}}

								</div>
					        </div>
							
					        <div class="col-xs-12 col-sm-6">
					            <div class="input-group group-costum-2">
					                <span class="input-group-addon " id="sizing-addon2">Correo</span>
									{{form.email}}

								</div>
					        </div>
					        <div class="col-xs-12 col-sm-6">
					            <div class="input-group group-costum-2">
					                <span class="input-group-addon " id="sizing-addon2">Username</span>
									{{form.username}} 

								</div>
					        </div>
					        <div class="col-xs-12 col-sm-12">
						        <input value="Guardar" type="submit" name="Editar" id="submit-button" class="contact-submit pull-right" type="submit">
						    </div>	
						</div>
					</form>
        		</div>
        	</div>
        	
        </div>
    </section>

	
{% endblock content %}
{% block extra_js %}
<script type="text/javascript">
	$('input[type=text]').addClass( "form-control" );
	$('input[type=email]').addClass( "form-control" );
</script>

{% endblock extra_js %}

templates/index.html
{% extends "base.html" %}
{% load solo_tags %}
{% block extra_css %}
    <link rel="stylesheet" href="/static/css/bootstrap-select.min.css">
    <link href="/static/css/font-awesome.css" rel="stylesheet">
{% endblock extra_css %}
{% block content %}
{% get_solo 'configuracion.SiteConfiguration' as site_config %}
<div id="carousel-id" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-id" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-id" data-slide-to="1" class=""></li>
        <li data-target="#carousel-id" data-slide-to="2" class=""></li>
    </ol>
    <div class="carousel-inner">
        {% for foto in site_config.fotosportada_set.all %}
            <div class="item {% if forloop.first %}active{% endif %}">
                <img  alt="{{foto.titulo}}" src="media/{{foto.foto}}" width="100%">
            </div>
        {% endfor %}
    </div>
    <a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

<section class="section-white no-padding">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                <div class="panel panel-search">
                   <div class="panel-heading">Búsqueda</div>
                    <div class="panel-body">
                        <form id="contact-form" class="contact form-busca" action="/actores/busqueda/" method="GET">
                            <div class="input-group">
                                {{search.q}}
                                <span class="input-group-btn">
                                    <input value="Buscar" id="submit-button" class="contact-submit" type="submit">
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

</section>
<!--begin blog -->
<section class="section-grey fedd_noticias">

    <!--begin container-->
    <div class="container">

        <!--begin row-->
        <div class="row margin-bottom-20">

            <!--begin col-md-12-->
            <div class="col-md-10 col-md-offset-1 text-center">
                <h2 class="section-title">Últimas noticias</h2>
            </div>
            <!--end col-md-12-->

        </div>
        <!--end row-->
        <!--begin row-->
        <div class="row">
            {% for obj in feed.entries|slice:':3' %}
            <!--begin col-sm-4 -->
            <div class="col-sm-4">

                <!--begin blog-item -->
                <div class="blog-item">

                    <!--begin popup image-->
                    <div class="popup-wrapper">
                        <div class="popup-gallery">
                            <a href="#"><img src="{{obj.media_content.0.url}}" width="100%"  alt="pic"></a>
                        </div>
                    </div>
                    <!--begin popup image -->

                    <!--begin blog-item_inner -->
                    <div class="blog-item-inner">

                        <h3 class="blog-title"><a target="_blank" href="{{obj.link}}">{{obj.title|truncatechars:75}}</a></h3>
                        <a class="blog-icons last"><i class="icon icon-user"></i> {{obj.author}}</a>
                        <p>{{obj.description|striptags|safe|truncatechars:250}}</p>

                    </div>
                    <!--end blog-item-inner -->

                </div>
                <!--end blog-item -->

            </div>
            <!--end col-sm-4-->
            {% endfor %}

            

        </div>
        <!--end row-->

    </div>
    <!--end container-->

</section>
<!--end blog -->
<section class="section-white small-padding">

    <!--begin container-->
    <div class="container">

        <!--begin row-->
        <div class="row">
            <!--begin col-md-6-->
            <div class="col-md-6 text-center wow fadeIn" data-wow-delay="0.15s">

                <h3>Mapeo de cadena de valor de cacao</h3>
                <div class="mapa-container">
                    <div id="map-canvas" style="width:100%; height:400px"></div>
                </div>

            </div>
            <!--end col-sm-6-->
            <!--begin col-md-6-->
            <div class="col-md-6">
                {% load flatpages %}
                    {% get_flatpages as flatpages %}
                        {% for page in flatpages %}
                            {% if page.url == '/informacion-inicio/' %}
                                <h3>{{page.title}}</h3>
                                <div class="medium-paragraph margin-bottom-40 text-left">
                                    {{ page.content|safe}}
                                </div>
                            {% endif %}
                        {% endfor %}
            </div>
            <!--end col-sm-6-->




        </div>
        <!--end row-->

    </div>
    <!--end container-->

</section>




{% endblock content %}

{% block extra_js %}
<script src="/static/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    $('#id_paises_labora, #id_tipo_organizacion, #id_participacion_cadena, #id_servicios, #id_intercambio, #id_tipo_actividad').selectpicker({
      style: 'btn-default',
      size: 4,
      liveSearch: 'true',
      title: '------'
    });

</script>
<script type="text/javascript">

    $( ".bootstrap-select" ).removeClass( "input-group-btn" );
    $( "#id_pais_sede" ).addClass("form-control");
    $( "#id_ambito_accion" ).addClass("form-control");
    $( "#id_tipo" ).addClass("form-control");
    $( ".form-busca #id_q" ).addClass("form-control");
    {% if search_text %}
        $(".form-busca #id_q").val("{{search_text}}");
    {% endif %}

</script>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBaguICGAyEp7DdwkG2Z-odTyjLVYMicmg" type="text/javascript"></script>
<script type="text/javascript" src="/static/js/markerclusterer.js"></script>
<script>
var markers = [];
function initialize()
{
    var infowindow = new google.maps.InfoWindow();
    var myLatlng = new google.maps.LatLng(13,-85);
    var myOptions = {
        zoom: 5,
        center: myLatlng,
    }

    var map = new google.maps.Map(document.getElementById('map-canvas'), myOptions);
    var bounds = new google.maps.LatLngBounds();
    var infowindow = new google.maps.InfoWindow();


    $.getJSON("{% url 'obtener-lista' %}", function(data){
        $.each(data, function(i, elemento){
            var latlng = new google.maps.LatLng(elemento.lat, elemento.lon);
            bounds.extend(latlng);
            var marker = new google.maps.Marker({
                position: latlng,
                map: map,
                title: elemento.nombre,
                // icon: image,
                item: '',
                id: elemento.id
            });
            markers.push(marker);

            // google.maps.event.addListener(marker, 'click', (function(mm, tt) {
            //     return function() {
            //         infowindow.setContent(tt);
            //         infowindow.open(map, mm);
            //     }
            // })(marker, elemento.nombre));

        });
        var markerCluster = new MarkerClusterer(map, markers);

    });

    //map.fitBounds(bounds);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
{% endblock extra_js %}




templates/notify_new_permiso.html
<html>
  <head></head>
  <body>
    <p>Usted tienen un nuevo mensaje de permiso</p><br>

    ------------ <br>
    {{mensajes|safe}}<br>

    ----------<br>

    <p> por favor si quiere otorgar permiso a este usuario: {{usuario}} siga
        el siguiente link.</p> <br>

    {{url}}

    <h1>Directorio Cacao</h1>
   </body>
</html>